# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d520e1d888138eb0f82c9b2f808dbe0d74ffcdb18b43f9d91b2c8d0ec4a68295ec20dd33431a1ccb550a0ad2851d1363c574debc9ecfb2d9b36c2cbec1d93726

test:
  secret_key_base: 5344471db98d22c9970cf41f1e743b44b976c436d032eace09e29b91e9789aab24b5169e414021694be504e2a6ac65eded21bde9a9f782f8c1f3d415bbdb29aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
